config/routes.rb
Rails.application.routes.draw do
  resources :singers
  resources :songs
  get 'commonshare', to: redirect("https://www.commshare.com/")
  get 'contact', to: "pages#about"
  get 'about', to: "pages#about"
  get 'error', to: "pages#error"

  devise_for :users
  resources :homes
  root 'homes#index'
  get "*path", to: redirect("/error")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  include Publish
end

app/models/concerns/sluggable.rb
module Sluggable

  extend ActiveSupport::Concern

  included do
    before_validation :set_default_slug, on: [:create, :update]

    def set_default_slug
      if !self.name.nil? && !self.name.empty? && ( self.slug.nil? || self.slug.empty? )
        self.slug = name.parameterize
      end
    end

    end

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/singer.rb
class Singer < Artist
  has_many :songs
  include Sluggable
  include Publish
  extend Publish
end

app/models/song.rb
class Song < ApplicationRecord
  #validates :title, presence: { message: 'you should enter a song title'}, uniqueness: true
  #validate :my_validation

  #validates_with NameValidator

  before_validation :set_slug
  belongs_to :singer, counter_cache: true

  def my_validation
    if title.length != 2
      errors.add(:title, "you have to have")
    end
  end
  def check_content
   content.length == 2
  end

  def set_slug
    if self.title.empty?
      throw :abort
    end
    self.slug = title.parameterize
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :password, confirmation: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :play_lists
end

app/models/validators/name_validator.rb
class NameValidator < ActiveModel::Validator
  def validate(record)
    if record.nil? || record.name.length <= 2
      record.errors.add(:name, 'need to be begger than 2')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  add_flash_types :success, :danger


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def hommes
    @Songs = Song.all.limit(100)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
    @title = "Get your music"
  end

  def about
    @title = "Get your music"
  end

  def error
  end
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  before_action :set_singer, only: %i[ show edit update destroy ]

  # GET /singers or /singers.json


  def index
    binding.pry
    @singers = Singer.all
  end

  # GET /singers/1 or /singers/1.json
  def show
    Singer.notes = [19, 20]
    puts Singer.new.pub
  end

  # GET /singers/new
  def new
    @singer = Singer.new
  end

  # GET /singers/1/edit
  def edit
  end

  # POST /singers or /singers.json
  def create
    @singer = Singer.new(singer_params)

    respond_to do |format|
      if @singer.save
        format.html { redirect_to singer_url(@singer), notice: "Singer was successfully created." }
        format.json { render :show, status: :created, location: @singer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /singers/1 or /singers/1.json
  def update
    flash[:success] = "singer updated !!"
    respond_to do |format|
      if @singer.update(singer_params)
        format.html { redirect_to singer_url(@singer), notice: "Singer was successfully updated." }
        format.json { render :show, status: :ok, location: @singer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /singers/1 or /singers/1.json
  def destroy
    @singer.destroy

    respond_to do |format|
      format.html { redirect_to singers_url, notice: "Singer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singer
      @singer = Singer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def singer_params
      params.fetch(:singer, {})
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    session[:user_id] = 4
    cookies.signed[:username] = { value: "mima", expires: 1.month.from_now}
    flash.now[:success] = "songs"
    @songs = Song.all
    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml { render xml: @songs}
    end
  end


  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    if @song.valid?
      respond_to do |format|
        if @song.save
          format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
          format.json { render :show, status: :created, location: @song }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    redirect_to songs_path, success: "updated successfully"
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/homes/index.html.erb
<div class="hero h-screen" style="background-image: url(https://placeimg.com/1000/800/arch);">
  <div class="hero-overlay bg-opacity-60"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-md">
      <% if  current_user %>
      <% else %>
        <li><%= link_to 'Sign up', new_user_session_path %></li>
        <li><%= link_to 'Sign in', user_session_path %></li>
      <% end %>
      <h1 class="mb-5 text-5xl font-bold">Hello there</h1>
      <p class="mb-5"> Enjoy your  Moments with music.</p>
      <button class="btn btn-primary">Get Started</button>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer items-center p-4 bg-neutral text-neutral-content">
  <div class="items-center grid-flow-col">
    <svg width="36" height="36" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
    <p>Copyright © 2022 - All right reserved</p>
  </div>
  <div class="grid-flow-col gap-4 place-self-center justify-self-end  items-center">
    <div class="flex items-center">
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
      <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <div class="">
      <%= image_tag("logos/logo.jpg", width:'50px') %>
    </div>
    <div class="dropdown">
      <label tabindex="0" class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
      </label>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'contact', contact_path %></li>
        <li><%= link_to 'commonshare', commonshare_path %></li>
      </ul>
    </div>
  </div>
  <div class="navbar-center">
    <a class="btn btn-ghost normal-case text-xl">Music Store</a>
  </div>
  <div class="navbar-end">
    <button class="btn btn-ghost btn-circle">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
    </button>
    <div class="avatar">
      <div class="w-10 h-10 rounded-full">
        <img src="https://placeimg.com/192/192/people" />
      </div>
    </div>
    <% if  current_user %>
    <% else %>
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <li><%= link_to 'Sign in', user_session_path %></li>
    <% end %>
  </div>
</div>

app/views/layouts/_songs.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl">Songs</h1>
  <%= link_to 'New song', new_song_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>

<div id="songs" class="min-w-full">
  <%= render @songs %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicStudio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/daisyui@2.39.0/dist/full.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
     <%= render "layouts/header" %>
      <main>
        <% if session[:sucsses] %>
          <div class="alert alert-success">
            <%= session[:sucsses] %>
          </div>
          <% session.delete(:sucsses) %>
        <% end %>
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name %>">
            <%= msg %>
          </div>
        <% end %>
        <div class="container mx-auto mt-28 h-screen">
          <%= yield %>
        </div>
      </main>
     <%= render "layouts/footer" %>

    <script>
      document.documentElement.setAttribute('data-theme', window.localStorage.getItem('theme'))
    </script>

    <%= javascript_importmap_tags %>
  </body>
</html>

app/views/pages/about.html.erb
<div>
  <h1 class="font-bold text-4xl">About Us</h1>
  <hr>
  <p><%= @title %></p>
</div>

app/views/pages/contact.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#contact</h1>
  <p><%= @title %></p>
</div>

app/views/pages/error.html.erb
<h1>page not exist</h1>
go to <%= link_to "home", root_path %>

app/views/play_lists/_form.html.erb
<%= form_with(model: play_list, class: "contents") do |form| %>
  <% if play_list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(play_list.errors.count, "error") %> prohibited this play_list from being saved:</h2>

      <ul>
        <% play_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/play_lists/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Play lists</h1>
    <%= link_to 'New play list', new_play_list_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="play_lists" class="min-w-full">
    <%= render @play_lists %>
  </div>
</div>

app/views/shared/_songs.html.erb
<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl">Songs</h1>
  <%= link_to 'New song', new_song_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>

<div id="songs" class="min-w-full">
  <%= render @songs %>
</div>

app/views/singers/_form.html.erb
<%= form_with(model: singer, class: "contents") do |form| %>
  <% if singer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(singer.errors.count, "error") %> prohibited this singer from being saved:</h2>

      <ul>
        <% singer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/singers/_singer.html.erb
<div id="<%= dom_id singer %>">
  <% if action_name != "show" %>
    <%= link_to "Show this singer", singer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this singer', edit_singer_path(singer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/singers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing singer</h1>

  <%= render "form", singer: @singer %>

  <%= link_to "Show this singer", @singer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to singers", singers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/singers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Singers</h1>
    <%= link_to 'New singer', new_singer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="singers" class="min-w-full">
    <% @singers.each do |singer| %>
      <%= singer.songs.map(&:title).join(',') %>
    <% end %>
  </div>
</div>

app/views/singers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New singer</h1>

  <%= render "form", singer: @singer %>

  <%= link_to 'Back to singers', singers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/singers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @singer %>

    <%= link_to 'Edit this singer', edit_singer_path(@singer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this singer', singer_path(@singer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to singers', singers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/songs/_form.html.erb
<%= form_with(model: song, class: "contents") do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_area :title, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :slug %>
    <%= form.text_field :slug, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= song.title %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this song", song, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this song', edit_song_path(song), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>


  <div class="card w-96 bg-base-100 shadow-xl">
    <figure><img src="https://placeimg.com/400/225/arch" alt="Shoes" /></figure>
    <div class="card-body">
      <h2 class="card-title">Shoes!</h2>
      <p>If a dog chews shoes whose shoes does he choose?</p>
      <div class="card-actions justify-end">
        <button class="btn btn-primary">Buy Now</button>
      </div>
    </div>
  </div>
</div>

app/views/songs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Show this song", @song, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/songs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Songs</h1>
    <%= link_to 'New song', new_song_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="songs" class="min-w-full">
    <%= render @songs %>
  </div>
</div>

app/views/songs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New song</h1>

  <%= render "form", song: @song %>

  <%= link_to 'Back to songs', songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/songs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @song %>

    <%= link_to 'Edit this song', edit_song_path(@song), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this song', song_path(@song), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to songs', songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>